# Setup
title: RRH Resources
baseurl: "/RHHR"
url: "https://jaizu.github.io"
paginate: 1
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Jaizu
  url: https://twitter.com/JaizuFangaming
  email: jaizu671@gmail.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: About
    url: /about

paginate_path: "/baseurl/page:num/"

defaults:
  - scope:
      path: "_posts/resource"
    values:
      type: "resource"
  - scope:
      path: "_posts/fangame"
    values:
      type: "fangame"
